import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/Navbar";
import Footer from "@/components/home/Footer";
import { Toaster } from "react-hot-toast";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="dark"
      lang="en"
      className={`${jakarta.variable} h-full antialiased`}
    >
      <body className="font-[family:var(--font-jakarta)] min-h-full flex flex-col">
        <Navbar />

        <main className="flex-1">
          {children}
          <Toaster position="top-right" />
        </main>

        <Footer />
      </body>
    </html>
  );
}